# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Seed"
license = "MIT"
licenselink = "https://github.com/keepitcomplicated/seed-web/blob/master/LICENSE.md"
description = "Theme for SEED Industries website"
homepage = "http://seed-universe.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Sveinn Davidsson"
  homepage = "http://keepitcomplicated.com/"

